### ISSUE TITLE
CLI command to generate PMTiles from GerryDB view(s)

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#11]
**Todo:**

- [ ] Write and test command
  - [x] locally
  - [ ] on prod
  - [x] Command should create copy as fgb first
- [x] Build table to store tileset paths and names
- [x] Build endpoint to fetch tileset paths (or `GET /api/document/{document_id}` should return path)
- [x] Create single-layer PMTiles for each received GerryDB view
- [x] Update bucket CORS

**Comment by raphaellaude** [comment]
**Todo:**

- [ ] Write and test command
- [ ] Create single-layer PMTiles for each received GerryDB view
- [ ] Update bucket CORS
