### ISSUE TITLE
Election data and partisan coloring / stats

### ISSUE THREAD

**Issue by mariogiampieri** [districtr/districtr-v2#99]
We will have to spec out further- presumably this will be fed from specific `gerrydb` views?

**Comment by cdonnay** [comment]
Peter will provide data for 10 different modules.

**Comment by raphaellaude** [comment]
Steps
- [ ] Add new data that Peter sent
- [ ] Create additional view(s) for partisan stats
- [ ] FE updates to populate the views

**Comment by nofurtherinformation** [comment]
![Image](https://github.com/user-attachments/assets/4d428fee-ea28-47da-8857-d2a339f27135)

<img width="948" alt="Image" src="https://github.com/user-attachments/assets/ce2ecea5-1072-4b1e-a256-3067a84821d9" />

**Comment by nofurtherinformation** [comment]
Closed with #334
